"use strict";
console.log("-".repeat(100));
console.log(5 + 3);
console.log("-".repeat(100));
console.log(5 + 3);
console.log("-".repeat(100));
console.log(5 + 3);
console.log("-".repeat(100));
console.log(5 + 3);
console.log("-".repeat(100));
